# Generated by Django 3.2.12 on 2022-05-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='title',
            field=models.CharField(default='a', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='hashtags',
            field=models.ManyToManyField(related_name='movies', to='collects.Hashtag'),
        ),
    ]
