# Generated by Django 3.2.12 on 2022-05-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collects', '0003_collection_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='on_main',
            field=models.BooleanField(default=False),
        ),
    ]
