# Generated by Django 3.2.12 on 2022-05-19 04:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collects', '0004_collection_on_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='movies', to='collects.Hashtag'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_collections', to=settings.AUTH_USER_MODEL),
        ),
    ]
