# Generated by Django 3.2.12 on 2022-05-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_review_user'),
        ('collects', '0006_alter_collection_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='collections', to='movies.Movie'),
        ),
    ]
