# Generated by Django 3.2.12 on 2022-05-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='default', max_length=16),
            preserve_default=False,
        ),
    ]
